backend:
  name: github
  repo: OlehLazurkevych/olehlazurkevych.github.io
  branch: main
  base_url: https://netlifyfunctionsoauthforgithub.netlify.app
  auth_endpoint: /.netlify/functions/oauth-start
  site_domain: olehlazurkevych.github.io # optional but recommended

site_url: https://olehlazurkevych.github.io
display_url: olehlazurkevych.github.io

logo:
  src: /assets/img/logo.png
  show_in_header: true

media_folder: "assets/uploads/cars"   # where images are stored in repo
public_folder: "/assets/uploads/cars" # how the site references them

collections:
  - name: "cars"
    label: "Cars"
    folder: "_cars"
    create: true
    slug: "{{slug}}-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "car" }
      - { label: "Дата публікації", name: "created_at", widget: "datetime", default: "{{now}}" }
      - { label: "Заголовок", name: "title", widget: "string", hint: "Наприклад: Land Rover Range Rover HSE" }
      - { label: "Вартість (USD)", name: "price_usd", widget: "number", required: false, hint: "Вартість вказати як ціле число без символів" }
      - { label: "Рік", name: "year", widget: "number", required: false }
      - { label: "Рік/Місяць", name: "alt_year", widget: "string", required: false, hint: "Альтернатива до поля Рік. Рік також бажано вказати." }
      - { label: "Двигун", name: "engine", widget: "string", required: false }
      - label: "Привід"
        name: "drive"
        widget: "select"
        required: false
        options:
          - { label: "Повний привід", value: "Повний привід" }
          - { label: "Передній привід",  value: "Передній привід" }
          - { label: "Задній привід",  value: "Задній привід" }
      - { label: "Під завдатком", name: "under_deposit", widget: "boolean", default: false, required: false }
      - { label: "На площадці", name: "on_site", widget: "boolean", default: true }
      # multi-photo list (any amount)
      - label: "Фотографії"
        name: "photos"
        widget: "list"
        required: false
        field:
          label: "Фото"
          name: "photo"
          widget: "image"
          media_folder: "/assets/uploads/cars"
          public_folder: "/assets/uploads/cars"
      - { label: "Опис", name: "body", widget: "markdown", required: false }
      - { label: "Відео посилання", name: "video_url", widget: "string", equired: false, hint: "https://www.instagram.com..." }
